### PR TITLE
Update TensorFlow interface to C backed version

### PR DESCRIPTION
**Pull request by riga**
I removed the Python-based interface `PhysicsTools/TensorflowInterface` and added the C-based interface from [this repo](https://gitlab.cern.ch/mrieger/CMSSW-DNN) to `PhysicsTools/TensorFlow`.

Changes to `DeepFlavourJetTagProducer`:

- Use the new interface
- Delete tensors in destructor
- Use pointer arithmetic in `tensor_fillers.h`

### CODE REVIEW

**Comment by pablodecm** [comment]
Hi @riga, the changes compiles as you left them. I have asked to include the model in the new format in the data externals (see https://github.com/cms-data/RecoBTag-Combined/pull/8) but in the meanwhile I have adapted path and minor details missing so I can start testing., I have an extra commit over this branch here https://github.com/pablodecm/cmssw/commit/278467a5b76ba65c6fbd798f221754ad044fac5c.

The commit changes the model path to the new location, changes from tensor to operation name (i.e. remove ":0" suffixes), handles Tensors as value instead of dynamically which should simplify the treatment and also I have to change slighly to be able to run batches of differents njets. I create first an empty Tensor and then per event I set the right dimension with init and then I define and remove inputs.

By copying locally the folder DeepFlavourV01_C to RecoBTag/Combined/data from https://github.com/pablodecm/RecoBTag-Combined/tree/deepflavour_C, I can test the whole thing, but I am getting a segmentation fault after starting to process the first event (was also before holding the Tensors as values). I do not know wether the origin is a misuse of your API or something else. Can you have a look to see what could I be missing?

PS: the graph does indeed load quite faster (100x)

Thanks,
Pablo

**Comment by riga** [comment]
Ok, I'm going to merge your changes and test it locally. Is `test/test_deep_flavour_cfg.py` suitable?

PS: I gave you push permissions to my branch.

**Comment by pablodecm** [comment]
@riga: yes, that test is suitable (process 10 events from a RelVal MINIAOD) as long as you copy the folder DeepFlavourV01_C to RecoBTag/Combined/data from https://github.com/pablodecm/RecoBTag-Combined/tree/deepflavour_C.

Do you want me to push the last changes to your fork or you do it?

**Comment by riga** [comment]
> Do you want me to push the last changes to your fork or you do it?

Already did this. I'm currently zeroing in on the problem.

**Comment by riga** [comment]
Ok, got it. Actually, there were two things that went wrong.

1. In the TF interface I was passing wrong pointers to the core method `TF_SessionRun`.
2. The use of `std::vector::emplace_back` with values (instead of pointers) indirectly calls destructors and copy constructors of the contained value type when the vector is rearranged (which happens on every emplace_back call). The compiler created an implicit copy constructor of the Tensor class which did some unwanted stuff. I wasn't really aware of that. In general I think it's not a good idea to provide a custom copy constructor to prevent copying large portions of memory accidentally. I disabled them now completely, which means that I had to use pointers again for storing tensors in the vectors. Hope this is fine for you.

For me, `test/test_deep_flavour_cfg.py` is running now =)

**Comment by pablodecm** [comment]
Hi @riga, great work fixing the segmentation fault. I changed to vectors to avoid destructor logic and raw pointers, but like this is fine. Alternatively, if they complain in the review process about it we could use a vector of unique_ptr to simplify the treatment and avoid explicit new and delete calls.

The small test also runs for me after pulling your latest changes. I will rebase your changes in the CMSSW PR branch tomorrow (I think there is no need to squash the commits, history is not so messy). I will run the whole battery of tests (hopefully the one that was occurring when using Python in FastSim does not occur anymore) and then if successful I will push to get it reviewed.

Thanks you,
Pablo

**Pull request merged**
